### ISSUE TITLE
Force Inedible items... edible.

### ISSUE THREAD

**Issue by KattofKits** [BoBAdministration/QA-Bug-Reports#154]
**Describe the Bug**
Whilst placing crystals, bones, anything "edible" normally through the foliage brush, even upon marking "force inedible" are still edible.

**To Reproduce**
1. Enter Spectate
2. Press X
3. Select an edible item such as SM_LProp_Crystal_01
4. Select "Force Inedible"
5. Leave X Menu
6. Leave Spectate
7. Attempt to eat inedible foliage
8. Eat what is inedible?

**Expected behavior**
Foliage marked as inedible should not be edible.

**Actual behavior**
Foliage marked as inedible IS edible.

**Screenshots & Video**
https://www.youtube.com/watch?v=71oyIKqC3Zs

**Branch Version**
Live

**Character Information**
Shimmer Tropeo, 1.22 naturally grown

**Additional Information**
Bugreport made on my own server due to dedicated testing servers down at the time of post.

**Comment by themurdock13** [comment]
I experienced the same bug and tried with multiple objects 

**Describe the Bug**
The force inedible toggle is supposed to prevent creatures from being able to eat/move objects 



**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1.  Logged into Dedicated Testing 3
2. Spawned in as Coach and set growth to 1.5
3. Enter Spectate and toggle on the Foliage tool 
4. Place down  multiple objects that should be edible but toggling the force inedible option 
5. become a creature that would normally be able to interact with the items 

**Expected behavior**
Items should not be able to be moved eaten or interacted with 

**Actual behavior**
All items were able to be moved by a 1.5 coach except for the foliage grade 7 tree


**Screenshots & Video**

https://youtu.be/f8U4o_aU49c


**Branch Version**
 Live Tester

**Character Information**
Coah  1.5 growth
