### ISSUE TITLE
flyer quick takeoff exploit using water 

### ISSUE THREAD

**Issue by themurdock13** [BoBAdministration/QA-Bug-Reports#330]
**Describe the Bug**
Birds have the ability to use  quick take of and the dart mechanic to reach accessive speeds when leaving the water 

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. have a flyer with quick take off 
2. enter water while flying 
3. dart out of the water and spam the space bar as you leave the water 

**Expected behavior**
normal art speed may be applied when leaving the water 

**Actual behavior**
birds leave water at excessive speeds and it scails with more quick take off and swiftness 

**Screenshots & Video**
[If applicable, add screenshots to help explain your problem, or attach a video/gif. You can do this by just pasting in your image(s)!

https://www.youtube.com/watch?v=hlzjLhUs36I&ab_channel=Corevus

**Branch Version**
Live.

**Character Information**
any flyer with quick take-off talent

**Comment by Vallyhalla** [comment]
Pred has tried to fix this many times and hasn't been able to as of this comment. Closing this for now since it's a well known issue.

**Comment by Undercooked-Mothman** [comment]
i see that this is closed, however id like to add a bit of information in case it gets worked on again in the future. Quick takeoff doesn't seem to effect the speed a huge amount, if at all (i have not looked at the actual speed values so take this with a grain of salt). You do not need to have any talents, nor do you need to be sprinting or even pressing w to get it to work. I have not been able to get it to happen by only pressing spacebar once when exiting the water, that *could* be because the timing is very precise. Pressing spacebar 2 or more times works. shallow angles when exiting the water make it much easier to replicate, however it is possible at any angle.
