### ISSUE TITLE
Egg continues to Float above water

### ISSUE THREAD

**Issue by Zi-Mom** [BoBAdministration/QA-Bug-Reports#348]
**Describe the Bug**
If you leave an egg when it is floating up in the water, it will continue to float going above the water and into the heavens

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1.  Logged into Open Console 
2. Took Egg
3. Had friend(Ceci) TP to me as bird, pick me up, take me under water
4. They dropped me and I waited for me to start ascending
5. While going up I left the egg
6. Watched egg float up in an attempt to reach the heavens

**Expected behavior**
Egg to either sink or stop at the top of the water

**Actual behavior**
Slowly goes up to the map ceiling

**Screenshots & Video**
https://www.youtube.com/watch?v=z_z46T3NyrM

**Branch Version**
Live.

**Character Information**
N/A Egg

**Additional Information**
Transferred from Vipe's Github Issue #10233

**Comment by Vallyhalla** [comment]
This seems to be the same problem as if someone crashes and their creature keeps moving forward, and when they return into the game their creature teleports back. I left the egg then went back in and the egg teleported back down to the water. Not sure if there's much we can do with this since like I said the game seems to be treating this as if someone crashed. Closing this for now since it's not a high priority problem and doesn't break the game.
