### ISSUE TITLE
B, A and S grade Text does not appear

### ISSUE THREAD

**Issue by D-Malik** [BoBAdministration/QA-Bug-Reports#641]
**Describe the Bug**
Whereas E-C grade appears on the screen, the blurbs do not appear for B-S grades. The only place where it appears is the Tab list or Trial list. Even then, sometimes it does not appear even there.

**To Reproduce**
Steps to reproduce the behavior in detail. Please include ALL steps, even menial ones.
1. Log into Live Branch
2. Have a partner with you
3. Grow with that same partner until B-S grade would appear

**Expected behavior**
Blurbs appear for B, A and S grade.

**Actual behavior**
There are no fun messages or pop ups.

**Screenshots & Video**
If applicable, add screenshots to help explain your problem, or attach a video/gif. You can do this by just pasting in your image(s)!

**Branch Version**
Live, Tester

**Character Information**
Any creature, must attain B grade at the very least.

**Additional Information**
Any map, any weather

**Labels:**
Live Branch
Tester Branch
Text
Art Bug

**Comment by Thy-Vipe** [comment]
Should be fixed. There was an integer squishing because the object representing the handle to the task id used the wrong int size to store the id of the task instance that is responsible for processing friendship events. This caused the queue item (widget that shows the friendship event) to get stuck internally forever.

**Comment by Xunaria** [comment]
Fixed
